- name: Create ansible user
  ansible.builtin.user:
    name: "{{ conf_servicing_service_user_name }}"
    system: true

- name: Create templated sudoers file for {{ conf_servicing_service_user_name }}
  ansible.builtin.template:
    src: debian.j2
    dest: /etc/sudoers.d/{{ conf_servicing_service_user_name }}
    owner: root
    group: root
    mode: "0440"

- name: Create additionally sudo accounts
  when: conf_servicing_sudo_accounts is defined
  block:
    - name: Create ansible user
      with_items: "{{ conf_servicing_sudo_accounts }}"
      no_log: true
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.pwd | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
        shell: /bin/bash
        groups:
          - sudo

    - name: Set authorized keys taken from url
      with_items: "{{ conf_servicing_sudo_accounts }}"
      when: item.ssh_key_public is defined
      no_log: true
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.ssh_key_public }}"
