- name: Gather ansible_os_family if needed
  when: ansible_os_family is not defined
  ansible.builtin.setup:
    filter:
      - ansible_os_family

- name: Running on Debian based distributions
  when: ansible_facts.os_family == "Debian"
  ansible.builtin.import_tasks: debian_based.yml
